name: " Pull Power Platform changes"

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: "Solution Name"
        required: true
        default: "PPSolution"
      environment:
        description: "Environment"
        required: true
        default: "Staging"
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

jobs:
  PullChanges:
    runs-on: [windows-latest]
    name: Pull changes from ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: BusinessCentralDemos/AL-Go-Actions/WorkflowInitialize@PowerPlatform
        with:
          shell: powershell
          eventId: "DO0091"

      - name: EnvName
        id: envName
        shell: powershell
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          $envName = '${{ inputs.environment }}'
          Add-Content -Path $env:GITHUB_OUTPUT -Value "envName=$envName"

      - name: Read settings
        uses: BusinessCentralDemos/AL-Go-Actions/ReadSettings@PowerPlatform
        with:
          shell: powershell

      - name: Read secrets
        uses: BusinessCentralDemos/AL-Go-Actions/ReadSecrets@PowerPlatform
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          settingsJson: ${{ env.Settings }}
          secrets: "${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext,${{ steps.envName.outputs.envName }}-EnvironmentName,${{ steps.envName.outputs.envName }}_EnvironmentName,EnvironmentName,projects"
      
      - name: read auth context
        id: authContext
        uses: BusinessCentralDemos/AL-Go-Actions/ReadAuthContext@PowerPlatform
        with:
          shell: powershell
          envName: ${{ steps.envName.outputs.envName }}
          environment: ${{ steps.envName.outputs.envName }}

      - name: TEST
        shell: powershell
        run: |
          echo ${{ env.authContext }} 
          echo ${{ env.deployTo }}
          echo ${{ env.environmentName }}

      - name: Export changes from Power Platform 
        uses: BusinessCentralDemos/AL-Go-Actions/PullPowerPlatformChanges@PowerPlatform
        with: 
          shell: powershell
          solutionName: ${{ inputs.solutionName }}
          directCommit: ${{ inputs.directCommit == 'Y' }}
          deploySettings: ${{ env.deployTo }} 
          authSettings: ${{ env.authContext }}